# Generated by Django 4.2.16 on 2024-11-13 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "sinp_nomenclatures",
            "0002_remove_nomenclature_active_nomenclature_status_and_more",
        ),
        ("sinp_organisms", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organismmember",
            unique_together={("member", "organism")},
        ),
        migrations.RemoveField(
            model_name="organismmember",
            name="member_level",
        ),
        migrations.AddField(
            model_name="organismmember",
            name="member_level",
            field=models.ManyToManyField(
                limit_choices_to={"type__mnemonic": "member_level"},
                related_name="member_level",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Niveau du membre",
            ),
        ),
    ]
