# Generated by Django 4.2.8 on 2023-12-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sinp_organisms", "0003_organism_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="organism",
            name="administrative_reference",
            field=models.CharField(  # noqa: DJ01
                blank=True, max_length=100, null=True, verbose_name="SIRET"
            ),
        ),
        migrations.AddField(
            model_name="organism",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
    ]
