# Generated by Django 4.2.8 on 2023-12-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sinp_nomenclatures", "0003_rename_item_nomenclature"),
        (
            "sinp_organisms",
            "0004_organism_administrative_reference_organism_enabled",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organism",
            name="geographic_area",
        ),
        migrations.AddField(
            model_name="organism",
            name="geographic_area",
            field=models.ManyToManyField(
                blank=True,
                help_text="Zone d'action géographique de l'organisme",
                limit_choices_to={"type__mnemonic": "geographic_area"},
                null=True,
                related_name="organism_geographic_area",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Zone géographique",
            ),
        ),
    ]
