# Generated by Django 4.2.8 on 2024-03-23 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sinp_nomenclatures", "0003_rename_item_nomenclature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sinp_organisms", "0005_remove_organism_geographic_area_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organism",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="organism",
            name="timestamp_create",
        ),
        migrations.RemoveField(
            model_name="organism",
            name="timestamp_update",
        ),
        migrations.RemoveField(
            model_name="organism",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="organismmember",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="organismmember",
            name="timestamp_create",
        ),
        migrations.RemoveField(
            model_name="organismmember",
            name="timestamp_update",
        ),
        migrations.RemoveField(
            model_name="organismmember",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="organism",
            name="geographic_area",
            field=models.ManyToManyField(
                blank=True,
                help_text="Zone d'action géographique de l'organisme",
                limit_choices_to={"type__mnemonic": "geographic_area"},
                related_name="organism_geographic_area",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Zone géographique",
            ),
        ),
        migrations.AlterField(
            model_name="organismmember",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
